//
// Created by Konrad Werys on 2019-08-15.
//

#ifndef LMFIT_OXFUNCTIONST1ADAPTERLMFITLEASTSQUARES_H
#define LMFIT_OXFUNCTIONST1ADAPTERLMFITLEASTSQUARES_H

#endif //LMFIT_OXFUNCTIONST1ADAPTERLMFITLEASTSQUARES_H
