var annotated =
[
    [ "Ox", null, [
      [ "TomatoOptions", "struct_ox_1_1_tomato_options.html", "struct_ox_1_1_tomato_options" ],
      [ "FactoryOfCalculators", "class_ox_1_1_factory_of_calculators.html", null ],
      [ "FactoryOfFitters", "class_ox_1_1_factory_of_fitters.html", null ],
      [ "FactoryOfFunctions", "class_ox_1_1_factory_of_functions.html", null ],
      [ "FactoryOfSignCalculators", "class_ox_1_1_factory_of_sign_calculators.html", null ],
      [ "FactoryOfStartPointCalculators", "class_ox_1_1_factory_of_start_point_calculators.html", null ],
      [ "Calculator", "class_ox_1_1_calculator.html", "class_ox_1_1_calculator" ],
      [ "CalculatorT1Results", "struct_ox_1_1_calculator_t1_results.html", "struct_ox_1_1_calculator_t1_results" ],
      [ "CalculatorT1Molli", "class_ox_1_1_calculator_t1_molli.html", "class_ox_1_1_calculator_t1_molli" ],
      [ "CalculatorT1Shmolli", "class_ox_1_1_calculator_t1_shmolli.html", "class_ox_1_1_calculator_t1_shmolli" ],
      [ "CalculatorT2", "class_ox_1_1_calculator_t2.html", "class_ox_1_1_calculator_t2" ],
      [ "Fitter", "class_ox_1_1_fitter.html", "class_ox_1_1_fitter" ],
      [ "ImageCalculatorT1", "class_ox_1_1_image_calculator_t1.html", "class_ox_1_1_image_calculator_t1" ],
      [ "Model", "class_ox_1_1_model.html", "class_ox_1_1_model" ],
      [ "ModelT1Shmolli", "class_ox_1_1_model_t1_shmolli.html", "class_ox_1_1_model_t1_shmolli" ],
      [ "ModelT1ThreeParam", "class_ox_1_1_model_t1_three_param.html", "class_ox_1_1_model_t1_three_param" ],
      [ "ModelT1TwoParam", "class_ox_1_1_model_t1_two_param.html", "class_ox_1_1_model_t1_two_param" ],
      [ "ModelT2ThreeParam", "class_ox_1_1_model_t2_three_param.html", "class_ox_1_1_model_t2_three_param" ],
      [ "SignCalculator", "class_ox_1_1_sign_calculator.html", "class_ox_1_1_sign_calculator" ],
      [ "SignCalculatorNoSign", "class_ox_1_1_sign_calculator_no_sign.html", "class_ox_1_1_sign_calculator_no_sign" ],
      [ "SignCalculatorRealImag", "class_ox_1_1_sign_calculator_real_imag.html", "class_ox_1_1_sign_calculator_real_imag" ],
      [ "SignCalculatorShmolli", "class_ox_1_1_sign_calculator_shmolli.html", "class_ox_1_1_sign_calculator_shmolli" ],
      [ "StartPointCalculator", "class_ox_1_1_start_point_calculator.html", "class_ox_1_1_start_point_calculator" ],
      [ "StartPointCalculatorBasic", "class_ox_1_1_start_point_calculator_basic.html", "class_ox_1_1_start_point_calculator_basic" ],
      [ "StartPointCalculatorShmolli", "class_ox_1_1_start_point_calculator_shmolli.html", "class_ox_1_1_start_point_calculator_shmolli" ],
      [ "TestData", "class_ox_1_1_test_data.html", "class_ox_1_1_test_data" ],
      [ "TestImage", "class_ox_1_1_test_image.html", "class_ox_1_1_test_image" ]
    ] ],
    [ "CalculatorT1", "class_calculator_t1.html", null ],
    [ "CalculatorT2ImageFilter", "class_calculator_t2_image_filter.html", null ],
    [ "KWUtil", "class_k_w_util.html", null ],
    [ "OxCalculatorT1Shmolli", "class_ox_calculator_t1_shmolli.html", null ]
];